# Generated by Django 4.2.7 on 2023-11-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_classattendancewithgeolocation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendancewithgeolocation',
            name='status',
            field=models.CharField(choices=[('proxy', 'Proxy'), ('verifie', 'Verifie'), ('standby', 'Standby')], default='standby', max_length=10),
        ),
    ]
