# Generated by Django 4.2.7 on 2023-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_classattendancewithgeolocation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='token',
        ),
        migrations.AlterField(
            model_name='classattendancewithgeolocation',
            name='status',
            field=models.CharField(choices=[('proxy', 'Proxy'), ('verifie', 'Verified'), ('standby', 'Standby')], default='standby', max_length=10),
        ),
    ]
