# Generated by Django 4.2.7 on 2023-11-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_geolocation_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falseattempt',
            name='token',
        ),
    ]
