# Generated by Django 4.2.7 on 2023-11-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_falseattempt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falseattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
    ]
