# Generated by Django 4.2.7 on 2023-11-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_rename_end_time_subjectclass_attendance_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclass',
            name='class_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='class_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
