# Generated by Django 4.2.7 on 2023-11-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_subjectclass_class_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendancewithgeolocation',
            name='status',
            field=models.CharField(choices=[('proxy', 'Proxy'), ('verified', 'Verified'), ('standby', 'Standby'), ('flaggers', 'Flaggers')], db_index=True, default='standby', max_length=10),
        ),
    ]
