# Generated by Django 4.2.7 on 2023-11-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_classattendancewithgeolocation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclass',
            name='class_start_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
