# Generated by Django 4.2.7 on 2023-11-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_subjectclass_class_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='falseattempt',
            name='creation_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='falseattempt',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.subjectclass'),
        ),
    ]
