# Generated by Django 4.2.7 on 2023-11-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_falseattempt_creation_time_falseattempt_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FalseAttempt',
            new_name='FalseAttemptGeoLocation',
        ),
        migrations.RenameModel(
            old_name='GeoLocation',
            new_name='GeoLocationDataContrib',
        ),
    ]
