# Generated by Django 4.2.7 on 2023-11-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_rename_falseattempt_falseattemptgeolocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendanceByBSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proxy', 'Proxy'), ('present', 'Present')], default='present', max_length=10)),
                ('class_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.classattendance')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
