# Generated by Django 4.2.7 on 2023-11-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_classattendancebybsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendancebybsm',
            name='class_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.classattendance', unique=True),
        ),
    ]
