# Generated by Django 4.2.7 on 2023-11-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_classattendancewithgeolocation_class_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendancebybsm',
            name='class_attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.classattendance'),
        ),
        migrations.AlterField(
            model_name='classattendancewithgeolocation',
            name='class_attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.classattendance'),
        ),
    ]
