# Generated by Django 4.2.7 on 2023-11-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_alter_student_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclass',
            name='class_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subjectclass',
            name='class_start_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
