# Generated by Django 4.2.7 on 2023-11-17 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0021_alter_subjectclass_class_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendancebybsm',
            name='marked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
