# Generated by Django 4.2.7 on 2023-11-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_projectconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mail',
            field=models.EmailField(db_index=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
