# Generated by Django 4.2.7 on 2023-11-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_alter_student_mail_alter_student_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclass',
            name='is_attendance_mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
