# Generated by Django 4.2.7 on 2023-11-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclass',
            name='merge_attendace_with_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.subjectclass'),
        ),
    ]
