# Generated by Django 4.2.7 on 2023-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_subjectclass_merge_attendace_with_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fcmtoken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
