# Generated by Django 4.2.8 on 2023-12-06 19:51

import attendance.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_student_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='classattendance',
            name='attendance_status',
            field=enumfields.fields.EnumField(default=3, enum=attendance.models.AttendanceStatus, max_length=10),
        ),
    ]
