# Generated by Django 4.2.8 on 2023-12-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_classattendance_attendance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classattendance',
            options={'permissions': [('can_mark_attendance', 'Can Mark Attendance')]},
        ),
    ]
