# Generated by Django 4.2.7 on 2023-12-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_alter_classattendance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classattendance',
            options={'permissions': [('can_mark_attendance', 'Can Mark Attendance'), ('can_send_notifications', 'Can Send Notifications')]},
        ),
    ]
