# Generated by Django 4.2.7 on 2023-12-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_projectconfiguration_version_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfiguration',
            name='MIN_SUPPORTED_APP_VERSION',
            field=models.CharField(default='1.0.0', max_length=12),
        ),
    ]
