# Generated by Django 4.2.7 on 2023-12-09 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0037_projectconfiguration_min_supported_app_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendancebybsm',
            name='marked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classattendancebybsm',
            name='status',
            field=models.CharField(choices=[('proxy', 'Proxy'), ('present', 'Present'), ('absent', 'Absent')], db_index=True, default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectclass',
            name='merge_attendace_with_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='attendance.subjectclass'),
        ),
    ]
