# Generated by Django 4.2.8 on 2024-01-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0041_subjectclass_class_topic_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectclass",
            name="class_topic_slug",
            field=models.CharField(max_length=300),
        ),
    ]
