# Generated by Django 4.2.8 on 2024-01-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0043_alter_subjectclass_class_topic_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectclass",
            name="super_batch_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
