# Generated by Django 4.2.8 on 2024-01-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0045_classattendance_is_injested"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectconfiguration",
            name="INJEST_ATTENDANCE_IN_REAL_TIME",
            field=models.BooleanField(default=False),
        ),
    ]
