# Generated by Django 4.2.8 on 2024-02-15 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0046_projectconfiguration_injest_attendance_in_real_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classattendance",
            old_name="creation_time",
            new_name="created_at",
        ),
    ]
