# Generated by Django 4.2.8 on 2024-02-15 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0047_rename_creation_time_classattendance_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classattendance",
            old_name="created_at",
            new_name="created_time",
        ),
    ]
