# Generated by Django 4.2.8 on 2024-02-15 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0048_rename_created_at_classattendance_created_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classattendance",
            old_name="created_time",
            new_name="date_created",
        ),
    ]
