# Generated by Django 4.2.8 on 2024-02-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0049_rename_created_time_classattendance_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="classattendancebybsm",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="classattendancewithgeolocation",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
