# Generated by Django 4.2.8 on 2024-02-15 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "attendance",
            "0051_rename_date_created_classattendance_date_updated_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="classattendance",
            name="date_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
