# Generated by Django 4.2.8 on 2024-02-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0052_alter_classattendance_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectconfiguration",
            name="CRON_TOKEN",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
