# Generated by Django 4.2.8 on 2024-02-17 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0053_projectconfiguration_cron_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectconfiguration",
            options={
                "permissions": [("can_sync_gsheet", "Can Sync Attendance with Gsheet")]
            },
        ),
    ]
