# Generated by Django 4.2.8 on 2024-02-23 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0055_alter_projectconfiguration_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classattendance",
            options={
                "permissions": [
                    ("can_mark_attendance", "Can Mark Attendance"),
                    ("can_send_notifications", "Can Send Notifications"),
                    ("verify_false_attempt", "Verify False Attempt GeoLocation"),
                    ("can_injest_to_scaler", "Can Injest to Scaler"),
                ]
            },
        ),
    ]
