# Generated by Django 4.2.8 on 2024-02-25 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0057_studentgroup_studentgroupitem_studentgroup_students"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentgroupitem",
            unique_together={("student", "student_group")},
        ),
    ]
