# Generated by Django 4.2.8 on 2024-02-25 12:25

import attendance.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0058_alter_studentgroupitem_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectClassStudentGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_policy",
                    enumfields.fields.EnumField(
                        default=0,
                        enum=attendance.models.AttendanceStatus,
                        max_length=10,
                    ),
                ),
                (
                    "student_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.studentgroup",
                    ),
                ),
                (
                    "subject_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.subjectclass",
                    ),
                ),
            ],
            options={
                "unique_together": {("subject_class", "student_group")},
            },
        ),
    ]
