# Generated by Django 4.2.8 on 2024-02-25 12:28

import attendance.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0059_subjectclassstudentgroups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectclassstudentgroups",
            name="attendance_policy",
            field=enumfields.fields.EnumField(
                default=0,
                enum=attendance.models.SubjectClassStudentGroups.AttendancePolicy,
                max_length=10,
            ),
        ),
    ]
