# Generated by Django 4.2.8 on 2024-06-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0060_alter_subjectclassstudentgroups_attendance_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectclass",
            name="is_attendance_by_geo_location_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
