# Generated by Django 4.2.8 on 2024-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0061_alter_subjectclass_is_attendance_by_geo_location_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectclass",
            name="is_attendance_mandatory",
            field=models.BooleanField(default=True, help_text="dont use this field"),
        ),
    ]
